### ISSUE TITLE
Problem with setting up [Latest version]

### ISSUE THREAD

**Issue by SMS221** [zPeanut/Hydrogen#24]
> Configure project :
Found AccessTransformer: hydrogen_at.cfg
Version string '1.5-beta_2' does not match SemVer specification
You should try SemVer : http://semver.org/

> Task :decompileMc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':decompileMc'.
> GC overhead limit exceeded

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 40s
5 actionable tasks: 4 executed, 1 up-to-date

**Comment by ProfKambing** [comment]
unbuilt version is unstable download the stable and built version at https://github.com/zPeanut/Hydrogen/releases/tag/1.5

**Comment by zPeanut** [comment]
try adding `org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=4096m -XX:+HeapDumpOnOutOfMemoryError` to your gradle.properties file

**Comment by zPeanut** [comment]
also i accidentally forgot to update the gradle build file in 1.5, is fixed in 1.6 however!

**Comment by SMS221** [comment]
> try adding `org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=4096m -XX:+HeapDumpOnOutOfMemoryError` to your gradle.properties file

Where do i find the gradle.properties file?, and why does it says Version string '1.5-beta_2' does not match SemVer specification

**Comment by zPeanut** [comment]
if you set it up with the 1.6 version the semver specification should be met, also gradle.properties is in the directory you cloned the repo in

**Comment by zPeanut** [comment]
actually let me add a gradle.properties file to the repo

**Comment by zPeanut** [comment]
try using the current 1.7-dev repo now, i added the options to the properties. to your semver specifications: thats not an error, its basically forge telling you to refer to [semantic versioning](https://semver.org/) which "1.5-beta_2" does not follow. this is fixed in the latest release but its usually just a warning which you would normally ignore

**Comment by zPeanut** [comment]
i guess i can close this now, reopen if you have any further problems
