### ISSUE TITLE
Loading screen

### ISSUE THREAD

**Issue by QianHeJ** [zPeanut/Hydrogen#28]
Cloud Please OverWrite the method <startgame> in Minecraft.java to write a new loading screen

**Comment by zPeanut** [comment]
i mean its a cool idea but i wouldnt really like that since its supposed to be a "ghost client"

**Comment by QianHeJ** [comment]
That's OK. It is simply a suggestion！It is up to you...

**Comment by zPeanut** [comment]
closed due to not adding it
