### ISSUE TITLE
HitAnimation

### ISSUE THREAD

**Issue by QianHeJ** [zPeanut/Hydrogen#33]
How About Writting a Hit Animation 
by overwritting renderItemInFirstPerso！
Hope to be adopted...tks！
Hydrogen！The Best Ghost Client based on Mixin！

**Comment by zPeanut** [comment]
it was initially supposed to be in it, but it would conflict with other mods such as oldanimations since id have to overwrite the method so i decided not to add it

**Comment by QianHeJ** [comment]
Thanks for your answer
