### ISSUE TITLE
(feature) auto w tap (suggestion)

### ISSUE THREAD

**Issue by fawwaz1234** [zPeanut/Hydrogen#4]
what is w tap?

w tap is a strategy that requires you to run and hit massive knockback to your opponents.

how does this module works?

everytime you hit an enemy while running the knockback will be very high. Therefore, everytime you hit the opponent it will reset your run and you can hit him again (and the cycle goes)

**Comment by fawwaz1234** [comment]
this is just a concept/suggestion i dont mind if you dont want to add this. :v

**Comment by zPeanut** [comment]
will look into this

**Comment by zPeanut** [comment]
added in 1.4.
