### ISSUE TITLE
Reach doesn't work

### ISSUE THREAD

**Issue by LifeTecLover999** [zPeanut/Hydrogen#41]
Reach doesn't work at all. Checked the code and there doesn't seem to contain code for reach.

**Expected behavior**
Reach would work

**Actual behavior**
Same reach as in vanilla

**Desktop (please complete the following information):**
 - OS: MacOS 12.1 Monterey
 - Version: 1.11.2
 - Other mods: OptiFine

**Comment by zPeanut** [comment]
will look into this

**Comment by zPeanut** [comment]
should be fixed in 1.11.3
