### ISSUE TITLE
more bends

### ISSUE THREAD

**Issue by Vitalasy** [zPeanut/Hydrogen#43]
More bends module like in novo.It is ported to 1.8.9 from a mod called mo's bends [https://github.com/mobends/MoBends](url).it adds very sexc animations to the game.

**Comment by zPeanut** [comment]
cant u just like add this to your mods folder 
![chrome_NQ3HLaHkCn](https://user-images.githubusercontent.com/25800857/149657930-b9e5de8a-88b7-4b12-a7c7-84d585029554.png)

**Comment by Vitalasy** [comment]
alr
