### ISSUE TITLE
Tab Menu (Player List) Darkens Enchantment Glint

### ISSUE THREAD

**Issue by tanyachaff** [zPeanut/Hydrogen#46]
**Describe the bug**
If the tab menu is held, enchantment glints will invert (darken).

**To Reproduce**
1. Place an item with enchantment glint in hotbar.
2. Hold tab, and observe the item.

**Expected behavior**
The glint should remain the same.

**Actual behavior**
The glint darkens, along with sections of the hotbar.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 1.8.9

**Comment by zPeanut** [comment]
will look into this, probably a problem with the implementation of the old tab system with the animations module. did you happen to have the animations module on during your observation?

**Comment by tanyachaff** [comment]
No, regardless of animations being on/off this still occured

**Comment by zPeanut** [comment]
https://user-images.githubusercontent.com/25800857/151794548-3720f140-78e1-410f-9b5e-0b6eca37b674.mp4

i honestly cant seem to reproduce this bug

**Comment by tanyachaff** [comment]
Apologies, this seems to be a conflict with the mod [better tab 2.1](https://piped.kavin.rocks/watch?v=7HWFjQmsisk). Strangely enough I wasn't having this issue prior to upgrading from version 1.9 to 1.12 though.

Closing as it may be nicer to include this mod's functionality within the client instead of fixing a one-off
