### ISSUE TITLE
Visual Glitches (Flickering Sneak Effect)

### ISSUE THREAD

**Issue by tanyachaff** [zPeanut/Hydrogen#47]
**Describe the bug**
At various intervals, the player sneak effect POV will rapidly flicker in bursts. When the sneak button is held, it stops.

**To Reproduce**
1. Play on a server for a short period of time.
2. Observe flickering.

**Expected behavior**
Nothing should happen!

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 1.8.9

**Comment by zPeanut** [comment]
can you further elaborate on what flickers, or show a video showcasing the bug?

**Comment by tanyachaff** [comment]
When sneaking, the player's POV drops down a little (client side). The issue is that at random periods of time, this "sneak" effect will rapidly activate and deactivate in bursts (per tick?) regardless of if the sneak button is held. This makes the screen look like it's flickering, however the fact that holding the sneak button will stop it from happening leads me to believe it's probably related to this.

**Comment by zPeanut** [comment]
i think this should be fixed in c65d512 , i however could only get to inconsistently reproduce this bug so if you still encounter this bug, feel free to open another issue
