### ISSUE TITLE
magnet

### ISSUE THREAD

**Issue by fawwaz1234** [zPeanut/Hydrogen#5]
if u stand near a block it will pull u to the block

**Comment by zPeanut** [comment]
can you provide video footage of this happening`?

**Comment by fawwaz1234** [comment]
https://streamable.com/ssvm19

**Comment by zPeanut** [comment]
what modules do you have enabled?

**Comment by fawwaz1234** [comment]
none

**Comment by zPeanut** [comment]
https://streamable.com/zwhf33 i cant really reproduce it, does it always happen or does it also happen when the mod is not installed?

**Comment by fawwaz1234** [comment]
yes, i think i'll keep using 1.4 b2 for now

**Comment by zPeanut** [comment]
try running hydrogen as a stand alone mod because i could not see any reason why this could come up. (i.e. in forge alone)

**Comment by fawwaz1234** [comment]
still not working {optifine+hydrogen)

**Comment by fawwaz1234** [comment]
i even ran it on multimc to test it still doesnt work

**Comment by fawwaz1234** [comment]
i suggest u try running 1.4 on ur minecraft

**Comment by fawwaz1234** [comment]
reinstalled it still not working hmm

**Comment by fawwaz1234** [comment]
1.4 b2 works fine tho

**Comment by zPeanut** [comment]
is 1.4.1 working?

**Comment by fawwaz1234** [comment]
nope still having the same issue

**Comment by zPeanut** [comment]
should be fixed in 1.4.2.
