### ISSUE TITLE
if it is possible to make it into exe injection client :Q

### ISSUE THREAD

**Issue by SakurajimaMai02** [zPeanut/Hydrogen#50]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zPeanut** [comment]
what

**Comment by zPeanut** [comment]
no

**Comment by Vitalasy** [comment]
> no

it certainly is i saw a client like yesterday the jar can be executed just like an exe and work for forge while you can also use the same jar by putting it in mods

**Comment by zPeanut** [comment]
yes it is possible but i wont do it

**Comment by Morten-Renner** [comment]
What are the benefits of this?
